### ISSUE TITLE
Issue with USE_WINDOWS_CONDITION_VARIABLES define

### ISSUE THREAD

**Issue by mikcom** [shtejv/ARDrone-Control-.NET#10]
I have followed recommendation in the updated Readme.txt file:
//-----------------------------------
Please uncomment the line
"#define USE_WINDOWS_CONDITION_VARIABLES"
in vp_os_signal_dep.h.
//-----------------------------------
1.  The line #define USE_WINDOWS_CONDITION_VARIABLES was already UNcommented in vp_os_signal_dep.h.
2.  Leaving it “as is” (uncommented) compiles project fine, however it throws an exception DLLNotFoundException (ARDroneDll.DLL) on “Startup” as described
3.  If, however, I _comment_ the line "#define USE_WINDOWS_CONDITION_VARIABLES" then project still compiles fine and runs OK without exception when pressing “startup” button.

Compilation and runtime environment:

Windows XP SP3
Visual Studio 2010
Win SDK 7.1 (though it also compiles OK with WinSDK  7.0A, which is supplied with VS 2010)
DirectX SDK (June 2010)
SDL 1.2.14
JDK (latest)

Therefore, it is either I’ve missed something or there is misprint and the line "#define USE_WINDOWS_CONDITION_VARIABLES" should be _commented_, rather than UNcommented for Windows XP

**Comment by shtejv** [comment]
You're right, it should be commented
