### ISSUE TITLE
Checksum failed

### ISSUE THREAD

**Issue by ClintH** [shtejv/ARDrone-Control-.NET#11]
Hi,

When running the sample code, there is a constant stream of errors such as the following. Everything seems to work OK, but letting you know in case this is something that needs fixing. Thanks for releasing the API!

[Navdata] Checksum failed : -858993460 (distant) / 31762 (local)
Tag 19 is not a valid navdata option tag

The second number (after the slash) varies, but the checksum failed number is always the same.

**Comment by shtejv** [comment]
Hmm, there could be a problem with your navboard sending incorrect information (I already had to change the navboard once). I don't get this error. But I'll watch out for it.
