### ISSUE TITLE
Problem Building - SDL Not Found even after defining directory in properties.

### ISSUE THREAD

**Issue by paralin** [shtejv/ARDrone-Control-.NET#12]
Hi,

Even after following the readme line for line I am getting this error:
error C1083: Cannot open include file: 'SDL.h': No such file or directory   

Here is my properties file:
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="UserMacros">
    <WinSDKDir>C:\Program Files\Microsoft SDKs\Windows\v7.1</WinSDKDir>
    <DXSDKDir>C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)</DXSDKDir><SDLDir>C:\Libraries\SDL</SDLDir>
  </PropertyGroup>
  <PropertyGroup>
    <_ProjectFileVersion>10.0.30319.1</_ProjectFileVersion>
  </PropertyGroup>
  <ItemGroup>
    <BuildMacro Include="WinSDKDir">
      <Value>$(WinSDKDir)</Value>
    </BuildMacro>
    <BuildMacro Include="DXSDKDir">
      <Value>$(DXSDKDir)</Value>
    </BuildMacro>
    <BuildMacro Include="SDLDir">
      <Value>$(SDLDir)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>

Thanks,
Christian

**Comment by paralin** [comment]
Sorry, got it to work eventually.

**Comment by shtejv** [comment]
Glad you got it to work.
