### ISSUE TITLE
High CPU with Xbox 360 controller

### ISSUE THREAD

**Issue by jbalat** [shtejv/ARDrone-Control-.NET#13]
Hi my experience is with VB6 but following your instructions I have managed to build the project in win7 vs2010. It connected and ran fine with keyboard. I had some issues when trying to connect my Xbox 360 controller.
- Cpu usage above 95% at one stage caused network dropout just when I was about to take off
- right stick was not detected (in windows this is seen as x and y rotation)
- also battery % was not available.
- When trying to map another joystick with not enough buttons it would be great to be able to map keyboard as well.

It will be some time before I have enough knowledge to address these myself. Are you able to help ?

Just an update 13-Jan - I noticed that I get 100% usage even with keyboard. Is ther anything you can do to reduce this ?

**Comment by shtejv** [comment]
CPU usage is about 10-12% for me .. are you using the WPF or the Windows Forms project?
Normally, WPF encounters higher CPU loads. If you have access to a profiler, you could run it and tell me where you encounter the highest CPU time.

As I don't own an XBox 360 controller, I cannot help with your controller right stick problem. But you could have a look at JoystickInput.cs and debug this class. Maybe the axis is missing in the list of recognized axes.

**Comment by jbalat** [comment]
I reduced the framerate of the video to 1fps which made the cpu drop to 65% which is ok.
Besides not being able to detect all the axes I will be working on the following..
1. option to invert the axis (my yaw was the wrong way)
2. Option for Exponential rates (The controls are very twitchy)
3. Option to add deadband % (the controls do not recenter perfectly)

oops closed this issue by accident ?
