### ISSUE TITLE
UI doesn't reset correctly after shutdown

### ISSUE THREAD

**Issue by TheRedWolf** [shtejv/ARDrone-Control-.NET#14]
On initial startup, connecting to the drone works properly and the camera images and nav data displays correctly, however on hitting shutdown various elements of the UI will no longer update when reconnected to the drone. The video box is no longer updated and no drone controls will operate the drone. Navdata still appears to be intermittently updated.

I've only had a brief look at the code so far, but it looks like this is occuring in or below the arDroneControl object rather than in the form code.

Not sure if I should place this as a separate issue given it is relatively minor, but the LED animation function is set off by one compared to the selection in comboBoxLedAnimations, so selecting a given animation actually plays the animation one above in the combobox.

**Comment by shtejv** [comment]
That's a known issue, I think it's an allocation problem in the underlying C code.

As it is not vital, this bug will be fixed in future versions.

**Comment by shtejv** [comment]
The bug should be fixed in the new version. Have a try.
