### ISSUE TITLE
The solution built successfully, but when I am trying to run it its giving an error.

### ISSUE THREAD

**Issue by mittalarpit** [shtejv/ARDrone-Control-.NET#15]
Unable to start program
'<path>\Ardrone\bin\Debug\ARDroneAPI\API\ARDroneAPI.lib'

The specified file is an unrecognized or unsupported binary format.

Could someone help me with how to fix this problem

Thanks

Arpit

**Comment by shtejv** [comment]
You need to set a different start program ... Unfortunately, Visual Studio saves the start project in a user specific file, so every user must set it once.

The correct start project would be ARDroneUI_WPF

**Comment by mittalarpit** [comment]
Thanks a lot! It worked.. Its an awesome API.. Too good..

Arpit
