### ISSUE TITLE
UI starts lagging after Startup

### ISSUE THREAD

**Issue by ppeso** [shtejv/ARDrone-Control-.NET#16]
After startup everything seems to be ok. Command window shows "connected to drone" and videostream works. As soon as I click on any button, the UI starts lagging. The drone can take off but hardly reacts to keyboard inputs. CPU load is 100%.

When building solution a warning considering ARDrone.UI.vshost.exe appears twice but can be skipped. Maybe this has something to with this issue..

thanks

**Comment by shtejv** [comment]
This is an issue that didn't come up on our systems. I'm afraid that I really cannot reconstruct it.

If you could profile the project, maybe we could gather some insights into this problem.

**Comment by ppeso** [comment]
I just figured out, this problem appears only on Win XP 32. Compiling on Win 7 64 works well.

For Win XP 32 I just followed the readme instructions. I commented "define USE_WINDOWS_CONDITION_VARIABLES" but I was wondering why it is not necessary to uncomment  "define USE_PTHREAD_FOR_WIN32" although it must be done in the win32 SDK example.

The warning messages I mentioned above say something like: "Microsoft.DriectX.directInput.dll is trying to carry out a managed execution within the lock of the OS-loader". The other one considers "Microsoft.DriectX.dll". (translated from German, so it might be incorrect..)

thanks
ppeso

**Comment by shtejv** [comment]
This bug was hard to track, back then. To avoid these situations in the future, I will follow a new approach:
There will be a new C# only backend in the next version of the drone control library. When this is done, I hope that all backend-related issues will vanish.

**Comment by shtejv** [comment]
The all new version is out, so I hope that the issue can be closed ... if there is still a problem, please open a new issue.
