### ISSUE TITLE
No video 

### ISSUE THREAD

**Issue by jim2v** [shtejv/ARDrone-Control-.NET#18]
Hi,

It's great that you wrote this and open sourced it!

However, I have been struggling for many hours trying to get video to show up.  I'm running Windows 7 professional. 
netstat -s shows that some packets have been discarded, and this number increases while the app is connected to the drone.
Running wireshark shows no udp 5555 packets.  I've disabled windows firewall and uninstalled the other firewalls, tried tweaking network settings (such as MTU) with netsh, all to no avail.   Can anyone please suggest anything else I could try, since I'm out of ideas.

Thanks in advance,
Jim

**Comment by shtejv** [comment]
To get rid of these problems, I'm currently working on a radical new approach. I'm converting the C++ source files to a C# only backend. I hope that this will eliminate all backend related problems.

At least, we will have more detailed error messages when I'm done with that.

**Comment by firesq38** [comment]
Can't wait for the updated release, thanks for your hard work

**Comment by shtejv** [comment]
The all new version is out, so I hope that the issue can be closed ... if there is still a problem, please open a new issue.
