### ISSUE TITLE
Interface for DI and testability

### ISSUE THREAD

**Issue by AndersMalmgren** [shtejv/ARDrone-Control-.NET#25]
Thanks for all your hard work guys!
Each time a new version of the API is released i have to go through some steps to make it work with my program.
The biggest one is that I have to extract an interface from the DroneControl class, this is beacuse i use dependency injection to inject the concrete DroneControl class into my class instance.

Maybe we could have this interface in the main code repository so that we to not to redo this job everytime?
This is how my interface looks as of current version of API, note that I've added a public method Init and removed the constructor that takes a droneconfig, this is to make it easier for DI.

```
public interface IDroneControl
{
    void Init(DroneConfig droneConfig);
    event DroneErrorEventHandler Error;
    event DroneConnectionStateChangedEventHandler ConnectionStateChanged;
    event DroneNetworkConnectionStateChangedEventHandler NetworkConnectionStateChanged;
    Bitmap BitmapImage { get; }
    ImageSource ImageSourceImage { get; }
    DroneData NavigationData { get; }
    InternalDroneConfiguration InternalDroneConfiguration { get; }
    bool IsConnecting { get; }
    bool IsConnected { get; }
    bool IsFlying { get; }
    bool IsHovering { get; }
    bool IsEmergency { get; }
    DroneCameraMode CurrentCameraType { get; }
    bool CanTakeoff { get; }
    bool CanLand { get; }
    bool CanCallEmergency { get; }
    bool CanCallReset { get; }
    bool CanSendFlatTrim { get; }
    bool CanFlyFreely { get; }
    bool CanEnterHoverMode { get; }
    bool CanLeaveHoverMode { get; }
    bool CanSwitchCamera { get; }
    Size FrontCameraPictureSize { get; }
    Size BottomCameraPictureSize { get; }
    double FrontCameraFieldOfViewDegrees { get; }
    double BottomCameraFieldOfViewDegrees { get; }
    void ConnectToDrone();
    void Disconnect();
    void SendCommand(Command command);
    bool IsCommandPossible(Command command);
}
```

This also makes the host program easier to UnitTest... Thanks again!

**Comment by shtejv** [comment]
A common interface will be a good idea. If you could integrate it into the current version, just send a pull request and I'll merge it into my base line.
