### ISSUE TITLE
1.7.4 video codec support

### ISSUE THREAD

**Issue by AndersMalmgren** [shtejv/ARDrone-Control-.NET#29]
Hi Thomas. Do you have any plans of porting the new codec decoder from the 1.8 sdk? I dont think I have time for such a big port right now. I will how ever look into the losting connection problem...

**Comment by shtejv** [comment]
No, I certainly don't want to go through bit manipulation again. But there is a fallback in the protocol when using custom profiles.

This way. you can still use the H.264 codec.If there are other freeware solutions for the P.264 version, Iet me know.

**Comment by AndersMalmgren** [comment]
I've started to looking at implementing a opencl decoder of both decoders this way you do not decode from the main CPU which will make the SDK use less resources. You will ofcourse need a opencl capable GPU but most modern GPU's support that. This will however give me no time to look into the connection problem, so I hope some else is looking into that.
