### ISSUE TITLE
AR Drone 1.7.4 not responding to keyboard/joystick input

### ISSUE THREAD

**Issue by aaron9589** [shtejv/ARDrone-Control-.NET#35]
Not sure what I'm doing wrong, however I have compiled the source myself and am able to establish a successful connection to the drone with video link and the ability to read telemetry. I can take off and land, however the control surfaces don't seem to work, despite the values being read on the display as I move the joystick. Any ideas as to what I can do?

**Comment by shtejv** [comment]
Hmm, I've never tested the drone with firmware 1.7.4, but Parrot did make some changes with each new versions.

It's best to consult the developer handbook. I've included the old versions (the ones that I used for building the program). Maybe the syntax has changed. In this case, it would not be that difficult to change the command classes.

**Comment by aaron9589** [comment]
it turns out that hover mode wasn't turned off, it seems to work fine with 1.7.4... Thanks again!

**Comment by dingjianrui** [comment]
Hi aaron9589, have you already fixed this issue? Do you mean that before i send Pitch,Roll,Yaw,Gaz command i have to turn off hover mode ?

**Comment by shtejv** [comment]
The progressive command seems not to have changed ... also, it works for my two drones using the newest firmware version 1.7.11.
