### ISSUE TITLE
Joy stick/Keyboard not working

### ISSUE THREAD

**Issue by uxmanz** [shtejv/ARDrone-Control-.NET#37]
I have ardrone with latest firmware version 1.7.11

joy stick movement and keyboard buttons do change roll pitch..etc values  but drone  do not move....

but i can takeoff,land,turn off hover mode do various other functions with both keyboard and joystick except i cant move it any where!!!.....what am i missing

and i disabled hover mode!!.....

also the application  crashes some times at line number 100 of  NetworkWorker.cs

thanks

**Comment by shtejv** [comment]
Hmm, this bug should already be removed by now. Are you using the newest version of the drone control library? A few weeks ago, the bug should have been removed. Please verify that you are using the newest version by downloading the the master branch again and building it from scratch. If there is still a problem, I'll try to figure out why.

What is the exact error message you get when NetworkWorker crashes?

**Comment by uxmanz** [comment]
well i some how made that work... i dont know what exactly was problem.....it wasn't taking any input from joy stick or keyboard....I placed a test button and gave yaw command.... after that it started working....

thanks for reply!...
