### ISSUE TITLE
control_level: problem

### ISSUE THREAD

**Issue by uxmanz** [shtejv/ARDrone-Control-.NET#40]
Hi.

There is a combined yaw mode AT command. I have looked in the code but couldn't find. Can you please tell me how to enable and disable this mode and where to amend the code.

thanks

**Comment by uxmanz** [comment]
Is this thread/git alive???

**Comment by shtejv** [comment]
I don't  have much time to work for the drone control library, sorry.

What you're looking for is the progressive command. It can be used for changes in pitch, roll and yaw.
