### ISSUE TITLE
Any plans to modify this wonderful code for the New AR Drone 2.0?

### ISSUE THREAD

**Issue by mass017** [shtejv/ARDrone-Control-.NET#42]
I have just received the newest version of the AR Drone (2.0).  With low to no expectations of this working with it (due to the firmware difference) I downloaded and compiled the code.  Amazingly I am able to Takeoff, Control and Land.  I am having problems with the Video (it doesn't work) and the HUD Controls (Altitude, Windspeed, Direction) do not seem to work either.  I'm just curious if there are any plans to rework this code for any changes in the 2.0 version?  Thanks in advance.

**Comment by shtejv** [comment]
I'm sorry, but I won't have the time to work on supporting this firmware version. Since I'm working on this alone, it would just eat up too much of my project time.
