### ISSUE TITLE
 ArDrone Detection Forms throws nullreference

### ISSUE THREAD

**Issue by BoraKoc** [shtejv/ARDrone-Control-.NET#43]
i can start detection forms, but after i hit connect button program throw an exception : nullreference from image.width in CopyBitMap function. i think program cannot connect ar drone but even if i change values from DroneConfig.cs there is no change. 

thanks.

**Comment by shtejv** [comment]
The detection forms app is not as sophisticated as the full-blown "normal" app. You need to connect to the drone's manually through the Windows WiFi menu.
Then, you can start the form detection app. This should do the trick.
