### ISSUE TITLE
It isn't possible to change configuration values in the drone

### ISSUE THREAD

**Issue by miguelbarros** [shtejv/ARDrone-Control-.NET#6]
The parrot drone has a set of configuration values (changed using the AT*CONFIG command - for instance, maximum altitude) that could be very usefull to set from the c# world. However, there isn't a c# way to do this - it could be usefull to create some exports/dllimports to do this.

Should I place this kind of suggestions here? These are not actually "issues", but more like "usefull new features" - i don't want to clutter this space...

**Comment by shtejv** [comment]
This is the right place for such suggestions, so feel free to place them here.

Some of the commands could be very useful (the maximum altitude command is almost necessary). The only limiting factor here is time ... If you want to contribute, feel free to fork the code and send us a pull request if you have developed something worth sharing.

**Comment by shtejv** [comment]
The AT*CONFIG command is available in the new version of the drone control library. So feel free to use it.
