### ISSUE TITLE
Automatic detection of the drone wifi

### ISSUE THREAD

**Issue by miguelbarros** [shtejv/ARDrone-Control-.NET#7]
I don't know if I did something wrong, but to be able to put the drone to work i had to manually connect my laptop to the drone's wifi. It could be usefull (particularly for newbies) to have the application automatically detecting potential wifi networks that could be drones, and automatically connect to them (in case there was only one). 

This should be relativelly simple to do (assuming there is a way to know that a particular network belongs to a drone) and could increase the end user experience (less configuration to make the application work).

**Comment by shtejv** [comment]
You're right, you have to connect manually, atm.
And you're right, there are good network libraries for Windows, so connecting to the drone is not very hard.

**Comment by shtejv** [comment]
The new version of the drone automatically connects to the drone's network if it could be found. Have a try.
